### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by IDKwhattoputhere** [tcptomato/ROad-Block#1]
Remove

    ||e-day.ro^
since it breaks the site.

I would advise you to use

    $third-party
more often in those cases to avoid potential site breakage.

I've read a few times now that certain links break when Profitshare is blocked.
https://github.com/gorhill/uBlock/pull/974#issuecomment-159614724
https://adblockplus.org/forum/viewtopic.php?p=145819#p145819
I can't investigate this but maybe you know where to find such links.

Remove analytics providers:

    ||js-agent.newrelic.com^
    ||gemius.pl^
    ||eu-gmtdmp.gd1.mookie1.com^
    ||addthis.com^$third-party
    ||static.chartbeat.com^
    ||script.crazyegg.com^
    ||asset.pagefair.com^

You should add the missing ads on nwradu.ro
![bitdefender](https://cloud.githubusercontent.com/assets/16030872/12302928/16d7ba6a-ba28-11e5-9f7a-f02498dfff24.jpg)
I don't know what it says but it looks like it's an ad(?)

**Comment by tcptomato** [comment]
* e-day.ro - that was my intent, the rule was a copy/paste artifact. It appears three lines down, with the right arguments
* profitshare whitelist  - I'm not so sure  whitelisting them is a good idea. Currently if you click on the affiliate link described there, you get this screen  http://imgur.com/f7YtNrm, where you can make a temporary or permanent exception for it. If you have it whitelisted, people could be tricked in clicking on that link.
*analytics providers: - removed

* nwradu - that one is a static jpeg ad, doesn't include half the internet in scripts. I'll ad it in the next commit if you really think it should be blocked.

**Comment by IDKwhattoputhere** [comment]
- Profitshare whitelist: Just be aware that this disqualifies your list for users who don't use uBlock (Origin) since they won't see the screen.

- nwradu: Of course it should be blocked. If it's an ad, block it.

Thanks for putting work into this.

**Comment by tcptomato** [comment]
* the list was planned for uBO. ABP has rolist on it's subscription page as a supplemental list. I doubt they'll accept two.

* i'll block it when I get home

I just want to do my part to improve the internet

**Comment by IDKwhattoputhere** [comment]
Just to add:
- ROList might not stay on adblockplus.org forever. If they decide there is a conflict in interests (not blocking certain ads for personal reasons) they might remove it.

- I see why you would consider not blocking a simple JPG. The purpose of adblockers however is to block all ads and if a site runs "acceptable ads" they can get whitelisted through the Acceptable Ads initiative: https://adblockplus.org/en/acceptable-ads#application

**Comment by tcptomato** [comment]
* ah, I noticed the not removing a friend's ad part. But I'm not sure about the whitelisting part. People could be tricked to click on them. I think if somebody really wants to follow the affiliate link they can disable the rule

* commited.

**Comment by tcptomato** [comment]
May I close the issue?

**Comment by IDKwhattoputhere** [comment]
Sure, all is fixed.
