### ISSUE TITLE
roboxfilme4k.com

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#100]
Pagină URL (necesar) `:https://roboxfilme4k.com/stuff/stuff_11/black_widow_vaduva_neagra_2021_film_online_subtitrat/11-1-0-956`
Screenshot (optional)  :
![screen](https://user-images.githubusercontent.com/79897301/129329755-67e9d29b-2f4f-4d07-8da5-26d6a4e60f56.jpg)
![screen01](https://user-images.githubusercontent.com/79897301/129329761-c558ccdb-7eca-4146-9060-1eaed7693b86.jpg)
![screen02](https://user-images.githubusercontent.com/79897301/129329764-600dfc3d-1fbb-454d-ab07-62452f92a75e.jpg)

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
This works fine to block ads: `roboxfilme4k.com##a[href^="https://www.udont2021.com/"]`

**Comment by tcptomato** [comment]
Done
