### ISSUE TITLE
onlinesubtitrat.com

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#101]
Pagină URL (necesar) `:https://www.onlinesubtitrat.com/film/523587-bad-sister`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
When I press the 'play' button from the videoplayer some pop-ups appear, one blocked from easylist filter and one in another tab with a website logo.

**Comment by tcptomato** [comment]
Does this site actually work? I just see it loads a jpg and it sets the ad link when clicking on play.

**Comment by andreewmat** [comment]
> Does this site actually work? I just see it loads a jpg and it sets the ad link when clicking on play.

That's the same problem I encountered too. I think it's just a joke, not a real website.
