### ISSUE TITLE
https://retete.unica.ro/

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#104]
Pagină URL (necesar) `:https://retete.unica.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
There are some placeholders on the page.
![imageedit_2_2427614592](https://user-images.githubusercontent.com/79897301/130572532-c68d6e64-17cb-4d18-9b57-252926a1695b.gif)

**Comment by tcptomato** [comment]
Done
