### ISSUE TITLE
https://www.petitchef.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#105]
Pagină URL (necesar) `:https://www.petitchef.ro/retete/acompaniamente/crema-tartinabila-kinder-bueno-cu-2-ingrediente-fid-1575541`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
There are ads placeholders.

**Comment by tcptomato** [comment]
Done
