### ISSUE TITLE
playtech.ro cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#106]
Pagină URL (necesar) `:https://playtech.ro/2021/internetul-dupa-30-de-ani-cate-site-uri-au-fost-cate-sunt-ce-s-a-schimbat-intre-timp/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
There are placeholders, like on the top of the page and between paragraphs.

**Comment by tcptomato** [comment]
Done
