### ISSUE TITLE
www.scritub.com

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#107]
Pagină URL (necesar) `:https://www.scritub.com/casa-gradina/PRELATE-DE-PISCINE-DE-VARA15736.php`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
There are placeholders between paraghraps.

**Comment by tcptomato** [comment]
Tried to get them, but couldn't find a way to catch all.
