### ISSUE TITLE
m.ziare.com ads

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#108]
Pagină URL (necesar) `:https://m.ziare.com/`
`https://m.ziare.com/stiri/urs-prins-capcana-barbat-cercetat-1698028`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.

**Comment by tcptomato** [comment]
Done
