### ISSUE TITLE
olx.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#109]
Pagină URL (necesar) `:https://www.olx.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
When I try to open a category from home page( e.g from "Auto, moto si imbarcatiuni" when I try to open "Autoturisme") I can't select it. If I disable Road-block is working fine.

**Comment by uBlock-user** [comment]
Caused by `@@tracking/ninja.js$script,domain=olx.ro`, disabling the filter fixes it.

**Comment by mapx-** [comment]
if removing the exception above is causing other issues just add:

`@@||google-analytics.com/analytics.js$script,domain=olx.ro`

**Comment by mapx-** [comment]
idk, @tcptomato could tell us I guess

**Comment by MicrowaveSnacks** [comment]
`https://www.olx.ro/`

<details> <summary> Screenshot: </summary>

![image](https://github.com/tcptomato/ROad-Block/assets/134642685/286b72bf-5b08-4040-9fdd-5b0f02d4b3e4)

</details>

```
olx.ro##[data-id="promo"]
```
