### ISSUE TITLE
trafictube.ro nu mai merg filmele

### ISSUE THREAD

**Issue by scarbit** [tcptomato/ROad-Block#11]
Salut initiativa, dar am o problema de cateva zile.
Nu imi mai merg filmele pe trafictube,
Cred ca au schimbat aia ceva ca imi zice ca nu am js activat, dar eu il am,

**Comment by elaur** [comment]
Ce folosesti Adblock Plus sau uBlock origin ? Am testat cu uBlock Origin si functioneaza.

![uBlock Origin Trafictube](http://f.cl.ly/items/3k1O3c1g1Q0C00191v1E/Screen%20Recording%202016-06-24%20at%2011.37%20am.gif)

**Comment by scarbit** [comment]
AdBlock cu uBlock imi zice lista outdated.

**Comment by scarbit** [comment]
Confirm ca merge cu uBlock (nu imi mai zice outdated).
Cu Adblock ... nu merge.

**Comment by tcptomato** [comment]
Ce versiune de Adblock folosesti ? ( Adblock plus). 
Verifici te rog ca Adblock foloseste ultima versiune a listei de filtre.

**Comment by scarbit** [comment]
Adblock Plus 
Version 1.12

**Comment by tcptomato** [comment]
In options la Adblock Plus ce iti apare in dreptul listei ? Presupun ca failed.

**Comment by scarbit** [comment]
m-am prins.... nelogat merge OK , logat nu mai merge.

**Comment by tcptomato** [comment]
Nu pot reproduce problema la mine. Ai putea posta screenshoturi cu blockable items in cele 2 situatii ?

**Comment by scarbit** [comment]
Scuze am fost in concediu.
![image](https://cloud.githubusercontent.com/assets/20117227/16998194/0b0ce0e2-4ec1-11e6-99de-a2a4cb17c4ae.png)

**Comment by tcptomato** [comment]
Nu-i bai.  De atunci am rezolvat problema si au gasit alt mod sa strice adblockerul. Din pacate nu exista o solutie simpla. Cuget momentan la o solutie, dar trebuie sa vad daca si functioneaza.

**Comment by tcptomato** [comment]
Acum exista un fix temporar in lista, + o discutie filozofica despre modul ideal de a scapa de asemenea "featureuri" . Cand iar se strica fa te rog un issue nou.
