### ISSUE TITLE
www.hoinaru.ro ads

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#111]
Pagină URL (necesar) `:https://www.hoinaru.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
![imageedit_2_8843719481](https://user-images.githubusercontent.com/79897301/131878263-5b8b03a3-bc54-47f9-a3b1-7408ea204949.gif)
![imageedit_1_2206499102](https://user-images.githubusercontent.com/79897301/131878278-67db8d8a-8ec6-4964-aee0-5f97a8584849.gif)

**Comment by tcptomato** [comment]
Added a rule. Thanks
