### ISSUE TITLE
myradioonline.ro 

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#112]
Pagină URL (necesar) `:https://myradioonline.ro/kiss-fm`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
With Road enabled I see these anti-adblock:
![imageedit_2_2719301793(1)](https://user-images.githubusercontent.com/79897301/132061694-8d38dd24-5597-4c93-a340-f75374b5bc6d.gif)

I suggested only the placeholder inside the music player because the one from top it break the site when I tried to remove it with element picker. Maybe you can find a solution for that one too.

Also, when I press the "Arata arta si versurile albumului" a pop-up appear and tell me to disable ad-block. 

And this is how the music player should look if I disable ublock and I select "Arata arta si versurile albumului":
![screen01](https://user-images.githubusercontent.com/79897301/132061807-28fb9f9c-1db7-4338-8547-b38c97e83a03.jpg)

**Comment by sugarfreesweetener** [comment]
<details> <summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/113248817/191604061-03d56ab9-21e4-4628-83bd-240530da02f1.png)

</details>
