### ISSUE TITLE
www.protv.ro / www.stirileprotv.ro cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#115]
Pagină URL (necesar) `:https://www.protv.ro/`
Screenshot (optional)  : `https://stirileprotv.ro/stiri/actualitate/animatie-grafica-momentul-in-care-trenul-de-aterizare-al-avionului-din-cluj-a-luat-foc-pe-pista.html`

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
For protv.ro:
![imageedit_2_2717460411](https://user-images.githubusercontent.com/79897301/137617051-eeae64ff-b64c-4ed0-ab62-1b331c506d0f.gif)
![imageedit_1_6708243883](https://user-images.githubusercontent.com/79897301/137617052-1391e40a-3f7f-43ae-a791-35e990a55ab2.gif)
![imageedit_2_4366110550](https://user-images.githubusercontent.com/79897301/137617058-886c7320-714a-485a-8ada-c601b275a2ed.gif)
![imageedit_2_4385523163](https://user-images.githubusercontent.com/79897301/137617062-8f05e5be-f260-4afd-be3d-9372bbedc415.gif)

For stirileprotv.ro:
![imageedit_2_5429261174](https://user-images.githubusercontent.com/79897301/137617262-e27a46dd-cf03-4327-b530-08b0b14b9bf3.gif)

**Comment by S0dV** [comment]
@mapx-

**Comment by S0dV** [comment]
uBlock Origin's `uBlock filters` has / had filters for `stirileprotv.ro`
