### ISSUE TITLE
https://www.sport.ro/

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#116]
Pagină URL (necesar) `:https://www.sport.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
Grey ads banners on the page.

**Comment by tcptomato** [comment]
Can't reproduce.

**Comment by S0dV** [comment]
@mapx- https://github.com/uBlockOrigin/uAssets/commit/5780a108ec977ffafffae7dfa732eb2a07ad5d29

**Comment by S0dV** [comment]
spaces encountered with AG (with `RO-adblock` enabled) on `https://www.sport.ro/` & `https://stirileprotv.ro/`
