### ISSUE TITLE
reno.com

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#120]
Pagină URL (necesar) : `https://www.reno.ro/-t306101.html`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
`https://github.com/easylist/easylist/issues/10286`

**Comment by mapx-** [comment]
```
reno.ro##.profitshare
reno.ro##.adsense
```

**Comment by tcptomato** [comment]
Thanks
