### ISSUE TITLE
www.rasfoiesc.com cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#122]
Pagină URL (necesar) : `https://www.rasfoiesc.com/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
Placeholders aroudn this website. On the top of the page, on the bottom and a grey space on the right side.

**Comment by mapx-** [comment]
```
rasfoiesc.com##[style^="overflow:"]:has([data-ad])
rasfoiesc.com##[style^="overflow:"]:has([data-ad-slot])
rasfoiesc.com##td[height^="500"]
```

**Comment by tcptomato** [comment]
Thanks
