### ISSUE TITLE
Are you looking for maintainers?

### ISSUE THREAD

**Issue by S0dV** [tcptomato/ROad-Block#124]
Salut, @tcptomato cauți ... întreținători pentru această listă de filtre?

**Comment by tcptomato** [comment]
Maintainers, yes. But a good start would be to make some PRs first, to earn some trust as @mapx-  said. 

"On the Internet, nobody knows you're a dog"

**Comment by S0dV** [comment]
> Maintainers, yes. But a good start would be to make some PRs first, to earn some trust as @mapx- said.

am facut PR-uri, dar de pe alte conturi :)

**Comment by S0dV** [comment]
https://github.com/S0dV/RoWebImprover

**Comment by S0dV** [comment]
A, si adresesi anti ad blocking, @tcptomato ?

**Comment by tcptomato** [comment]
Poftim?

**Comment by S0dV** [comment]
> Poftim?

Era o întrebare; adresezi anti ad blocking ? Gen, lucrurile care se milogesc de utilizator să dezactiveze ad blocker-ul dacă-l detectează.

**Comment by tcptomato** [comment]
Am inteles. In principiu da. 

Te-as ruga sa faci PRuri cu filtrele care le vrei incluse, nu doar sa deschizi issue-uri generice.

**Comment by S0dV** [comment]
> Te-as ruga sa faci PRuri cu filtrele care le vrei incluse, nu doar sa deschizi issue-uri generice.

Ok

**Comment by S0dV** [comment]
@mapx- will antiantiadb filters for Romanian web sites be moved here?

**Comment by mapx-** [comment]
I'll think about it
