### ISSUE TITLE
dcnews.ro

### ISSUE THREAD

**Issue by S0dV** [tcptomato/ROad-Block#127]
Pagină URL (necesar) : `https://www.dcnews.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.

ad

**Comment by mapx-** [comment]
@S0dV  It's so difficult to provide some details ? specific page, screenshot, other stuff.
