### ISSUE TITLE
ziuanews.ro

### ISSUE THREAD

**Issue by S0dV** [tcptomato/ROad-Block#133]
Pagină URL (necesar) : `https://www.ziuanews.ro/`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.

ad

Should `ziuanews.ro###pub-top-container` be added or should a network filter be added?

**Comment by playonevideo** [comment]
https://github.com/user-attachments/assets/5333d6fa-2ec8-447e-b751-e8f4d0b8c9ff" />

`https://www.ziuanews.ro/stiri/europa-face-pasul-decisiv-spre-euro-digital-pe-a-dat-unda-verde-ce-se-intampla-cu-banii-cash-ce-se-schimba-pentru-romani-i-de-ce-ue-vrea-propria-moneda-electronica-1595168`

ad on bottom
