### ISSUE TITLE
nu m-am plictisit, dar sunteți amuzanți

### ISSUE THREAD

**Issue by zosoro** [tcptomato/ROad-Block#14]
minima logică ar spune "bă, ăsta tot schimbă url-ul imaginii, dar lasă numele div-ului același. hai să banăm div-ul, pentru că am fost speciali toată ziua ieri". 

ps: și incapabilitatea și încrâncenarea asta a voastră va fi utilă atunci când veți vrea să băgați filtrul default în adblock sau ublock.

**Comment by tcptomato** [comment]
Logica asta e asa o chestie, depinde de rezultatul dorit. N-avem de ce sa trecem la filtre cosmetice, cat timp cele statice functioneaza. Sau pe intelesul tau, n-are rost sa downloadez reclama si sa o ascund cat timp pot sa nu o downloadez. 

Chestia care nu ai observat-o e ca la fiecare schimbare de URL ai pierdut o ,posibilitate de a o hosta acolo, so keep 'em coming.

**Comment by zosoro** [comment]
> Chestia care nu ai observat-o e ca la fiecare schimbare de URL ai pierdut o ,posibilitate de a o hosta acolo, so keep 'em coming.

Discutabil. Uite de ce: http://www.zoso.ro/andreea-maneole-fashion-bulane/

**Comment by tcptomato** [comment]
Ce anume ar trebuit sa vad?

**Comment by zosoro** [comment]
Că, în încrâncenarea asta stupidă, banezi și ce nu trebuie.

**Comment by tcptomato** [comment]
Este cel mai eficient mod de a implementa filtrul respectiv. 

Deschide te rog un issue si da-mi o lista cu pozele ( ce nu sunt reclama ) ce le vrei whitelistuite ( ceea ce voi  face ).

**Comment by zosoro** [comment]
E mai simplu să blochezi doar imaginea aia. 
Am o listă de vreo 160 imagini de pe imgure.

**Comment by tcptomato** [comment]
> E mai simplu să blochezi doar imaginea aia. 

Discutabil. 

L-am scos. Dar sa ne intelegem, daca pui iar reclama acolo il voi reactiva, permanent.

**Comment by zosoro** [comment]
i love the smell of blackmail in the morning.

**Comment by tcptomato** [comment]
Tu ai impresia ca am vreo obligatie fata de tine, nu am. Ti-am facut o favoare, iar conditia era simpla, sa nu ma iei de fraier. Sau traiesti cu impresia daca scrii un script care uploadeaza reclama pe imgur de cateva ori pe minut, eu stau si scriu filtre pentru fiecare poza in parte.
