### ISSUE TITLE
scenefz.me is blocked

### ISSUE THREAD

**Issue by CrazyEyesDave** [tcptomato/ROad-Block#15]
Pagină URL (necesar) : scenefz.me
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.

scenefz.me e blocat, iar cand e adaugat la exceptii este tot overlay-ul paginii afisat aiurea.

**Comment by elaur** [comment]
Site-ul lor nu functioneaza in modul https, probabil navigatorul tau forteaza sa foloseasca o conexiune securizata https pentru care site-ul nu este setat.
Iti recomandam sa gasesti o alternativa la acest site.

**Comment by tcptomato** [comment]
De ce este blocat site-ul?

**Comment by tcptomato** [comment]
Ugh. Clona de original fara securitate. De bagat manual la exceptii. 

Daca te uiti in logger cand e bagat la exceptii poti vedea ce filtre mai sunt active si de unde vin ( cand faci click pe ele).
