### ISSUE TITLE
eg

### ISSUE THREAD

**Issue by S0dV** [tcptomato/ROad-Block#151]
**It seems to me like it contains / may contain gambling / betting-related suff**

`https://europeangaming.eu/portal/compliance-updates/2022/02/07/108657/esa-gaming-boosts-global-footprint-with-romania-licence/` => ads + ph

Are:
```
||europeangaming.eu/static/softswiss/CS_1280_600_2.gif$image
europeangaming.eu##[class*="banner"]
europeangaming.eu###mvp-leader-wrap
```
good filters?

**Comment by mapx-** [comment]
report at easylist
