### ISSUE TITLE
Some websites with ads

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#163]
Pagină URL (necesar) 
`https://www.autoexpert.ro/mercedes-amg-eqe-varianta-performanta-pentru-sedanul-electric/`

`https://www.promotor.ro/stiri-auto/cat-costa-arkana-cel-mai-frumos-suv-coupe-de-la-renault-dupa-reducerile-rabla-2022-18999224`

`https://carzz.ro/nissan-murano-25-dci-tekna-premium-posibilitate-rate-anunt_3036968.html`

`https://floteauto.ro/dacia-logan-tce-100-gpl-carte-castigatoare/`

Screenshot (optional)  :
Autoexpert:
![screen02](https://user-images.githubusercontent.com/79897301/154810965-5fefe6b9-c389-461a-a8fa-8ac71257ef95.jpg)
![screen03](https://user-images.githubusercontent.com/79897301/154810969-8128bf5c-db04-42bf-8c65-7303e82bb0fa.jpg)

Promotor:
![screen04](https://user-images.githubusercontent.com/79897301/154810975-c9899e00-8ed6-4dbf-8221-7b40cd6abc7f.jpg)

Carzz:
![screen06](https://user-images.githubusercontent.com/79897301/154810981-2fb100ee-bd4b-4872-9dbc-a734e0727a02.jpg)

Flote auto:
![screen07](https://user-images.githubusercontent.com/79897301/154810988-99ef663a-ce89-49d7-909e-50c6c8171835.jpg)

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.

**Comment by andreewmat** [comment]
@mapx `https://carzz.ro/autoturisme.html` ads with CarVertical here also. Thanks for your great work!

**Comment by andreewmat** [comment]
@mapx  `https://www.autovit.ro/anunt/bmw-seria-5-ID7GGPPg.html` ad here too
![screen02](https://user-images.githubusercontent.com/79897301/154823401-3efbdd65-816e-480d-af27-e95cacb06e8b.jpg)

**Comment by mapx-** [comment]
In this case we can keep it, it's really useful (a feature) getting directly the VIN from page going to carvertical where you can get the car history report.
