### ISSUE TITLE
dez.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#165]
Pagină URL (necesar) `:https://www.dez.ro/dezmembrez-audi-a6-c6-3-0-diesel-quattro--7412696.html`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
The images from the post doesn't appear.

**Comment by mapx-** [comment]
You should use uBO (uBlock Origin adblocker) => this issue has been already fixed for uBO (unbreak list) time ago

**Comment by mapx-** [comment]
well, I saw now .. it was you reported same issue in uBO Assets repository
