### ISSUE TITLE
kudica.ro

### ISSUE THREAD

**Issue by PerfectSalad** [tcptomato/ROad-Block#167]
Pagină URL (necesar) : `https://www.kudika.ro/articol/love/67921/exercitii-cuplu-care-pot-restabili-armonia-si-readuce-fericirea.html`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
- Spaces
- anti-adb

**Comment by BottledH2O** [comment]
`https://www.kudika.ro/articol/art-fun/74066/atacul-unei-profesoare-la-adresa-danei-budeanu-doamna-budeanu-s-a-adresat-profesorilor-ca-unor-caini-vagabonzi.html` - placeholder

```
kudika.ro###billboard
```
