### ISSUE TITLE
Moving uAssets (uBO) filters for RO sites here?

### ISSUE THREAD

**Issue by PerfectSalad** [tcptomato/ROad-Block#168]
Hello,

Do you plan on moving uAssets (uBO) filters for RO sites here? And also, @tcptomato are scriptlet filters (##+js / #%#//scriptlet ...) supported in this repository?

**Comment by mapx-** [comment]
It's not a problem using scriptlet filters here in a separate list included like this (in the RO list)

for example
`!#include RO-uBO.txt`

**Comment by PerfectSalad** [comment]
> 

ok, and what about uAssets filters for RO sites?
