### ISSUE TITLE
e-sanatatea.ro

### ISSUE THREAD

**Issue by PerfectSalad** [tcptomato/ROad-Block#171]
anti-adb encountered with AG

**Comment by PerfectSalad** [comment]
@tcptomato would you like to have this fixed here?

**Comment by mapx-** [comment]
no anti adb using uBO, do you get it only using AG ?

**Comment by mapx-** [comment]
ok, the filter bellow is fixing anti adb in uBO

@Yuki2718

maybe you could add to AG filters:
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js:5`
