### ISSUE TITLE
evmarket. ro

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#178]
Pagină URL (necesar) : `https://evmarket.ro/programul-rabla/promotii-rabla-2022-pentru-modelele-dacia-pe-gpl-24718/`

In Tor Browser, with uBO + ro-adblock lite filter list on `https://evmarket.ro/programul-rabla/promotii-rabla-2022-pentru-modelele-dacia-pe-gpl-24718/` scrolling is weird.

**Comment by mapx-** [comment]
It's `wordpress soledad theme`

add
`||evmarket.ro/wp-content/themes/soledad/*scroll$script`
