### ISSUE TITLE
stirileprotv.ro

### ISSUE THREAD

**Issue by BudEar** [tcptomato/ROad-Block#179]
unhidden things on `https://stirileprotv.ro/` (if there are filters in uAssets for these, could they be moved here for AG BE?)

**Comment by mapx-** [comment]
> unhidden things

Which ones ?

**Comment by BudEar** [comment]
> > unhidden things
> 
> Which ones ?

@mapx- I think the issue is addressed by:
```
! stirileprotv. ro ads
stirileprotv.ro##*:matches-css-before(content:/ADVERTISING/):remove()
stirileprotv.ro##.topBranding
stirileprotv.ro###topBranding
```
from uBlock Origin's 'uBlock filters' - its license can be found in https://github.com/uBlockOrigin/uAssets/blob/master/LICENSE

However, AdGuard Browser Extension (Chrome) doesn't include uBlock Origin's 'uBlock filters' by default as far as I know.

**Comment by mapx-** [comment]
https://github.com/tcptomato/ROad-Block/commit/c3f0fa6d8fb9f7261ead254e9cd316276bb68f62
