### ISSUE TITLE
Deblocati stiripesurse.ro

### ISSUE THREAD

**Issue by ArmynC** [tcptomato/ROad-Block#18]
Pagină URL (necesar) : stiripesurse.ro
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.

Siteul este blocat, din cate am vazut, a fost adaugat la ROAD FLAG.. el nu este un site de tip fantoma ci unul de analiza politica.. chiar daca are uneori clickbaituri la unele topicuri.. posteaza cel mai rapid unele newsuri "din spatele usilor inchise" si e foarte vizitat..

Multumesc!

**Comment by tcptomato** [comment]
Partea respectiva din lista e preluata si inspirata de aici: https://verificasursa.ro/ . Ideea fiind de a indica ca linkul respectiv duce la un site cu continut discutabil, utilizatorul putand decide daca vrea sa continue ( in cazul lui uBlock aparandu-ti pe pagina chiar buton de whitelist temporar/permanent).  

Cat timp siteul este listat pe verificasursa.ro, nu il vom scoate din flag.

**Comment by ArmynC** [comment]
In mare parte nu mi se pare adevarat.. eu zic ca e singurul site care merita sters din ROAD .. pana atunci eu o sa sterg lista (pana cand o repuneti) si sunt sigur ca multi o sa faca lafel.. + imi face conflicte cu siteul.. chiar daca-l deblochez.. Pana si multe televiziuni folosesc acest site ca si sursa breakingnews.. Multumesc pentru raspuns!
