### ISSUE TITLE
7est.ro

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#182]
Ads on:

- `https://www.7est.ro/`

- `https://www.7est.ro/2022/04/un-alt-proiect-cu-fonduri-europene-al-aeroportului-iasi-a-fost-aprobat-in-sedinta-de-cj-iasi/` -- I encountered an ad for what looked like wines there

**Comment by mapx-** [comment]
https://github.com/tcptomato/ROad-Block/commit/2d1b0c1dd90ae7eb43ab5a89b6c094b841367524
