### ISSUE TITLE
De blocat Integr8

### ISSUE THREAD

**Issue by ColourGrey** [tcptomato/ROad-Block#186]
Pagină URL: https://kmkz.ro/no-notifications/o-tanara-din-negresti-oas-abandonata-la-nastere-s-indragostit-de-tatal-natural-au

Pagina conține un link (https://central.integr8.digital/tr/c/r?url=https://agathalabs.ro/collections/consultatii-medicale) către ceea ce pare un server de reclame. Nu situl Agatha Labs trebuie blocat, ci cel al Integr8 care pare a fi un server de reclame. De notat că dacă mergeți pe https://integr8.digital nu veți găsi niciun fel de detalii cu privire la companie, dar după engleza foarte aproximativă a sitului probabil este ceva românesc, cu identitatea ascunsă.

**Comment by tcptomato** [comment]
Am blocat sciptul care incarca reclama.

**Comment by ColourGrey** [comment]
Am actualizat lista de filtre românești pentru uBlock, dar în continuare văd reclama. De ce?

**Comment by tcptomato** [comment]
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=ROU-1 

Ce data iti apare la last modified? Poti trimite un screenshot cu reclama?

**Comment by mapx-** [comment]
/prebid/* already in easylist

We could add 
`||integr8.digital^$third-party`

**Comment by tcptomato** [comment]
Yes, but we never defined that people have to have other filters active. I've added your rule.

**Comment by ColourGrey** [comment]
Am forțat încă o dată actualizarea filtrului românesc, și acum totul e bine. Poate că versiunea actualizată a listei nu se propagase încă, și procesul de actualizare descărca tot versiunea veche rămasă prin vreun cache de pe traseu?

**Comment by Branzeturi** [comment]
@ryanbr
