### ISSUE TITLE
Eroare 509 pe adblock.ro

### ISSUE THREAD

**Issue by ColourGrey** [tcptomato/ROad-Block#187]
Cine vizitează adblock.ro primește eroarea 509 cu textul explicativ "Bandwidth Limit Exceeded. The server is temporarily unable to service your request due to the site owner reaching his/her bandwidth limit. Please try again later."

**Comment by tcptomato** [comment]
Multumesc de report. Pare-se ca mod_deflate nu era activat pe server si a fost consumat traficul pentru luna aceasta. Pentru upgrade la trafic providerul vrea 600 lei, asa ca pentru luna aceasta serverul va returna 509. Lista nu este insa afecatate, pentru ca github e configurat direct ca adresa secundara.

**Comment by Branzeturi** [comment]
@tcptomato Pe ce perioada de timp?
