### ISSUE TITLE
Banda Zf.ro

### ISSUE THREAD

**Issue by 98c71be8** [tcptomato/ROad-Block#19]
Pagină URL (necesar) : zf.ro
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.

Urmatoarele elemente (banda zf.ro) nu sunt filtrate chiar daca sunt adaugate manual in lista de block

zf.ro##.banda-sticky-vp
zf.ro##.item-title
zf.ro##.wrap
zf.ro##.promo-strip-close
zf.ro##.enlarge

**Comment by tcptomato** [comment]
Ce browser si adblocker folosesti?

**Comment by 98c71be8** [comment]
Google Chrome Version 61.0.3163.100
Adblock Plus: 1.13.4

**Comment by tcptomato** [comment]
Am reprodus problema, din pacate nu are legatura cu lista. Pare a fi o problema cu Adblock Plus, care nu aplica filtrele cosmetice. Deschizi tu bug report la ei? Daca nu, o fac eu. 

Ca alternativa pe termen scurt, ai putea trece la Ublock Origin.

**Comment by 98c71be8** [comment]
Multumesc pt sfat voi testa Ublock Origin. Nu voi deschide caz la AdBlock -vad ca au introdus notiunea de acceptable criteria for Ads (https://adblockplus.org/acceptable-ads) iar ZF.ro este listat in lista lor de acceptable ads: https://easylist-downloads.adblockplus.org/exceptionrules.txt
