### ISSUE TITLE
problema http://www.prosport.ro/

### ISSUE THREAD

**Issue by snyper06** [tcptomato/ROad-Block#20]
Pagină URL (necesar) : http://www.prosport.ro/
Screenshot (optional)  : nu situ cum sa pun

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.
nu imi mai merge sa citesc articole pe prosport. primesc un mesaj de eroare legat de adblock si daca scot lista de romana merge

**Comment by tcptomato** [comment]
Ce browser si adblocker folosesti? Apare intotdeauna "eroarea"?

**Comment by snyper06** [comment]
hai ca am reusit sa adaug imagine, sper sa se vada. folosesc chrome cu adblock plus. apare destul de des, am incercat si de la calculatorul fratelui meu si tot la fel
![image](https://user-images.githubusercontent.com/32961309/31828800-0844c116-b5c4-11e7-8164-afe7f7584a83.png)

**Comment by tcptomato** [comment]
Acum am prins-o si eu.

Problema este ca pagina respectiva este generata de un script inclus in pagina principala, lucru care Adblock Plus nu poate filtra.

uBlock origin, poate face asta. Poti trece la el? ( Momentan am un filtru nuclear aici, si as vrea sa te rog sa vezi daca afecteaza functionalitatea siteului)

Daca nu poti, instala o extensie de genul NoScript si ar trebui sa scapi de rahat.

**Comment by snyper06** [comment]
m-am uitat putin. nu mai merg videourile cu ublock origin, cu adblock inca mai vad mesajul ala

http://www.prosport.ro/video/prosport-live/avancronica-etapei-prezentarea-tuturor-meciurilor-din-aceasta-stagiune-care-este-cel-mai-tare-duel-din-aceasta-etapa-16776343

**Comment by tcptomato** [comment]
Pe adblock nu se poate bloca, datorita limitarilor extensiei. De aceea ziceam ca ai putea incerca cu un addon gen NoScript.

Am adaugat acum o regula pentru video, fa te rog update la extensie.

**Comment by snyper06** [comment]
ah am incercat sa gasesc NoScript pentru chrome, dar am vazut ca e doar pentru firefox

**Comment by tcptomato** [comment]
Scuze, ziceam NoScript ca tip de extensie, nu ea anume. ScriptSafe e o varianta https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf?hl=en ( asta era doar alternativa in caz ca nu vrei/poti trece la ublock ).

**Comment by snyper06** [comment]
am incercat si extensia dar blocheaza si ea videourile

**Comment by tcptomato** [comment]
Pacat. Singura varianta atunci e ublock cu lista actualizata. Iti functioneaza asa?
