### ISSUE TITLE
zvj.ro

### ISSUE THREAD

**Issue by Zaharos** [tcptomato/ROad-Block#203]
``https://www.zvj.ro/`` => third-party `confortmedia.ro` connections

**Comment by sugarfreesweetener** [comment]
<details> <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/113248817/191598893-55e2f384-dfd2-433f-abd0-7592cef776f9.png)

</details>

```
zvj.ro##[class*="banner"]
zvj.ro#?#.boxstire2head:-abp-contains(Publicitate)
```

**Comment by playonevideo** [comment]
These ads on the right side

https://github.com/user-attachments/assets/785b9243-25d7-483e-8e2b-cd5917d40d83" />
https://github.com/user-attachments/assets/9aa57791-e4c4-4649-a678-11fcb538d629" />
https://github.com/user-attachments/assets/dd22f8b5-5dd1-42ec-9d2f-ae3f9e205170" />
