### ISSUE TITLE
Filter list not updating correctly

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#204]
@tcptomato I don't intend to be rude, but apparently when I tried to receive an update version of the `road-block light filter list`, I was getting some unexpected stuff.

I understand why you wouldn't want to pay a lot of money for web hosting, so... could downloads for the filter list be prioritized to a free CDN ? Thanks!

**Comment by mapx-** [comment]
>  I was getting some unexpected stuff

explain that

**Comment by tcptomato** [comment]
https://road.adblock.ro/lista.txt returns an account suspended error. I've contacted support about it. But the github list is configured as a secondary URL, so ublock should be able to download it anyway.

**Comment by tcptomato** [comment]
Got a reply

> S-au inregistrat atacuri de tip DDoS atat spre domeniu, cat si spre subdomeniul specitifcat, iar din motive de securitate, accesul public catre cele 2 a fost blocat temporar. De asemenea, nu incurajam astfel de continut pe serverele noastre.

I'll look in the weekend for an alternative host. Or another option would be to drop the dedicated domain and just use the github link as the only source. @mapx- What do you think?
