### ISSUE TITLE
Website nefunctional

### ISSUE THREAD

**Issue by GrPK** [tcptomato/ROad-Block#22]
Pagină URL (necesar) : Websiteul oficial
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.
Websiteul oficial a cazut si ublock nu poate face update la filtru. Situatia asta este de peste o saptaman. Vreo rezolvare posibila?

**Comment by tcptomato** [comment]
Multumesc de report. Serverul pe care era hostat websiteul ( si proxy-ul listei ) a avut mici probleme. L-am migrat si acum ar trebui sa fie totul functional. Poti confirma te rog ca s-a rezolvat la tine ?
