### ISSUE TITLE
ziarulevenimentul.ro - advertising

### ISSUE THREAD

**Issue by sugarfreesweetener** [tcptomato/ROad-Block#246]
`https://www.ziarulevenimentul.ro/stiri/invatamant`

```
ziarulevenimentul.ro##[href*="/adclick.php"]
ziarulevenimentul.ro##[href^="https://www.bursa.ro"]
```

`ziarulevenimentul.ro##[href*="/adclick.php"]`
https://user-images.githubusercontent.com/113248817/191371837-380b00ca-c764-4000-ab0b-1cf3e05f30d7.png

`ziarulevenimentul.ro##[href^="https://www.bursa.ro"]`
https://user-images.githubusercontent.com/113248817/191371965-f71db1aa-7e36-4d0b-8089-0d47803bcd1c.png

**Comment by propagandism** [comment]
`https://www.bursa.ro/petre-daea-anunta-ca-romania-va-continua-sa-permita-tranzitul-de-cereale-ucrainene-catre-state-terte-45095942`
![image](https://user-images.githubusercontent.com/131309438/233206323-20de261a-fd9c-48ad-90a3-75e251f296b4.png)
![image](https://user-images.githubusercontent.com/131309438/233206353-405f669e-0391-42e0-a518-124ffef9be41.png)
ads (I think the ones from the sidebar seem to swap) + space
