### ISSUE TITLE
Should filter for forum.softpedia.com be changed?

### ISSUE THREAD

**Issue by sugarfreesweetener** [tcptomato/ROad-Block#263]
Could it be changed to/with `forum.softpedia.com#?#.post_block:-abp-has([class^="guest"]):-abp-contains(Anunturi)` in order to avoid breakage?

https://github.com/tcptomato/ROad-Block/issues/161

**Comment by sugarfreesweetener** [comment]
I haven't encountered any breakage, but what if someone were to say "Anunturi" on the forum?

**Comment by FanOfRootBeer** [comment]
`https://forum.softpedia.com/topic/1211978-maini-fiabile-buget-4000%26-8364%3B/`

=> ad (mobile user agent + view)

<details> <summary> Screenshot: </summary>

![image](https://github.com/tcptomato/ROad-Block/assets/144071104/1c902dda-5d64-408d-85ec-0711357264d7)

</details>
