### ISSUE TITLE
b1tv.ro

### ISSUE THREAD

**Issue by sugarfreesweetener** [tcptomato/ROad-Block#286]
`https://www.b1tv.ro/externe/cristian-diaconescu-dupa-declaratiile-lui-viktor-orban-joaca-foarte-politic-la-nivel-inalt-intr-un-cadru-multilateral-ungaria-nu-scoate-o-vorba-suntem-noi-mai-vocali-decat-ei-video-1206655.html`

`https://views.b1tv.ro/track.js?v=1.4.4`

Could something like `.ro/track.js?$script,~third-party` be added? https://github.com/AdguardTeam/AdguardFilters/blob/2b4f5c78754f89ff6664aa0b9d46b7665acc8a4c/SpywareFilter/sections/specific.txt#L53 https://github.com/AdguardTeam/AdguardFilters/blob/2b4f5c78754f89ff6664aa0b9d46b7665acc8a4c/SpywareFilter/sections/specific.txt#L55

**Comment by sugarfreesweetener** [comment]
`https://www.playsport.ro/exclusiv-video-valeriu-iftime-pregateste-marea-lovitura-in-fotbalul-romanesc-unul-dintre-cei-mai-buni-stranieri-din-istoria-ligii-i-in-discutii-cu-fc-botosani-este-o-salvare-imensa-187404` `https://views.playtech.ro/track.js?v=1.4.5`

**Comment by sugarfreesweetener** [comment]
Should `~third-party` from the filter be removed?

**Comment by BlocksAds** [comment]
https://dexonline.net/definitie-masina

**Comment by BlocksAds** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15446

**Comment by mapx-** [comment]
?

**Comment by BlocksAds** [comment]
nevermind, I thought the filter wasn't working from previous testing
