### ISSUE TITLE
romaniatv.net

### ISSUE THREAD

**Issue by sugarfreesweetener** [tcptomato/ROad-Block#290]
maybe `romaniatv.net#?#.top:-abp-has([id="sam_branding"])` or `romaniatv.net##.height-sm-250`

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/113248817/192051646-7e61c97f-c594-4c5b-bed4-3711be375e4e.png)

</details>

**Comment by advertblocker** [comment]
`https://www.economica.net/vagoane-etajate-ale-cfr-calatori-au-iesit-de-la-reparatii-din-uzina-electroputere-vfu-pascani-video_664578.html` => relatively small placeholder under recommendations under article 

```
economica.net#?#.under:-abp-has([id^="SC_TBlock"])
```
