### ISSUE TITLE
www.autocobalcescu.ro 

### ISSUE THREAD

**Issue by mortyam** [tcptomato/ROad-Block#294]
Pagină URL (necesar) : `www.autocobalcescu.ro`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
Cookie pop-up on the website.
Suggested fitler:  `autocobalcescu.ro##.box_cookies`

**Comment by mapx-** [comment]
There are specialized filter lists for cookies / annoyances

For cookies => EasyList Cookie
Other annoyances + cookies =>Fanboy’s Annoyance

add one of them to your adblocker from here:
https://easylist.to/

**Comment by mortyam** [comment]
@mapx- I opened an issue to eassylist cookie but they said the site has a low number of visitiors and I should add the specific filter to "custom filters" into ublock. I thought this is a better place to ask.

Also,, here is another site that has cookie pop-up: `https://www.autokarma.ro/`

**Comment by mapx-** [comment]
The fact is EasyList Cookie already blocks the cookie on the site above ! You have to subscribe that list !

same for autokarma

**Comment by mortyam** [comment]
@mapx- But maybe there are people who use this list only because they don't need cosmetic filtering on other sites and don't use Easylist or other annoyance list, that's why I think is good to be here too but you choose if it's ok or not. Thanks anyway to for maintaining the list! 👍
