### ISSUE TITLE
jurnalul.ro anti-adb

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#295]
`https://jurnalul.ro/bani-afaceri/piata-muncii/cu-cat-ar-putea-creste-pensiile-romanilor-procentul-real-aplicat-de-la-1-ianuarie-2021-913592.html`
![image](https://user-images.githubusercontent.com/116905165/198685601-53ffffb6-6a39-4020-8e28-e87a78e15968.png)

**Comment by mapx-** [comment]
already fixed in unbreak list (uBO)

`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect-rule=google-ima.js:5`
