### ISSUE TITLE
bzi.ro

### ISSUE THREAD

**Issue by AntiAdvert** [tcptomato/ROad-Block#304]
`https://www.bzi.ro/luminita-anghel-10-ani-de-casatorie-artista-in-varsta-de-53-de-ani-nu-si-a-pierdut-niciodata-speranta-4286838` -> space + `Good Game Empire` ad

![image](https://user-images.githubusercontent.com/117537631/200136489-dd7d1d15-5b9a-405c-8fb7-1f7ef2bd5057.png)
![image](https://user-images.githubusercontent.com/117537631/200136495-5fbf6890-2f17-4e46-8a72-88ddc14d8842.png)

**Comment by grassfedtallow** [comment]
`https://www.bzi.ro/` => contains placeholder (scroll down a bit)
```
bzi.ro#?#.height-250:-abp-has(> [id^="div-gpt-ad"])
```
