### ISSUE TITLE
https://www.europafm.ro/live/ Ads

### ISSUE THREAD

**Issue by seba2282** [tcptomato/ROad-Block#32]
Pagină URL (necesar) : 
https://www.europafm.ro/live/

Screenshot (optional) :
[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.
![screenshot_2018-08-21-10-52-16](https://user-images.githubusercontent.com/16944478/44391640-afb9c200-a530-11e8-93ec-acd5f0b6d4de.png)

**Comment by tcptomato** [comment]
Fixed. Multumesc pentru report.

**Comment by seba2282** [comment]
Thank you.
