### ISSUE TITLE
dailybusiness.ro

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#327]
`https://www.dailybusiness.ro/`

spaces

`dailybusiness.ro##[data-banner]`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/117537631/201486746-8834badc-bd47-4894-bc82-f3fdd7596f6f.png)

</details>

**Comment by pilis1** [comment]
There are ad leftovers again.

**Comment by pilis1** [comment]
`https://www.dailybusiness.ro/economie/anaf-i-a-comunicat-lui-iohannis-un-milion-de-euro-si-i-a-solicitat-predarea-imobilului-512247/`

<img width="755" height="868" alt="Image" src="https://github.com/user-attachments/assets/0af1ba4f-92bd-4fad-9300-62ec49163a4d" />
