### ISSUE TITLE
peco-online.ro - revolut ad

### ISSUE THREAD

**Issue by BlocksAds** [tcptomato/ROad-Block#342]
Site: `https://www.peco-online.ro/index.php`

Steps to reproduce:
- Select "Benzina Standard"
- Type in the box near "Nume locatie", "bucuresti"

<details><summary> Screenshot: </summary>

![image](https://user-images.githubusercontent.com/122573224/212189743-9caf44d6-18d2-4071-ae71-81188dfbffce.png)

</details>

**Comment by advertblocker** [comment]
placeholders
```
peco-online.ro#?#.card:-abp-has(.adsbygoogle)
```

**Comment by grassfedtallow** [comment]
different ad

maybe:

```
peco-online.ro##tr[style="border: 2px red solid;"]
```
