### ISSUE TITLE
go4games.ro

### ISSUE THREAD

**Issue by BlocksAds** [tcptomato/ROad-Block#344]
Web page: `https://www.go4games.ro/stiri-si-articole/diverse/nvidia-imbunatateste-reflex-cu-suport-in-jocuri-noi-si-noi-dispozitive-compatibile-cu-aceasta-tehnologie-19355047/`

Space between photo and paragraph (on my screen at least)

`go4games.ro#?#.mg-bottom-10:-abp-has(> .strawberry-ads)`

btw @mapx- it looks like many `abp-has` rules from `road-block lite` could be changed (by adding `> `) -- it looks like in AdGuard for Windows, in my case `go4games.ro#?#.mg-bottom-10:-abp-has(.strawberry-ads)` didn't work as I would've expected.

edit: on `https://www.bursa.ro/omv-petrom-se-asteapta-sa-nu-plateasca-taxa-de-solidaritate-pentru-anul-fiscal-2022-49367847` with AdGuard for Windows only there seem to be some ads on the web page (on the right side, with the list enabled), while with uBO (and the list) the ads seem to get hidden -- seemingly fixed by adding `bursa.ro#?#.clearfix [href][target="_blank"][rel]:has(> [alt][title][style])` in AdGuard for Windows

**Comment by mapx-** [comment]
`> .strawberry-ads` does not work in uBO

report at AG repository for these cases
