### ISSUE TITLE
[NSFW] fileshare dot ro

### ISSUE THREAD

**Issue by BlocksAds** [tcptomato/ROad-Block#347]
**Warning: NSFW content (around the tinme I'm typing this)**

URL I found from search on DuckDuckGo: `http://www.fileshare.ro/e3241694`

```
! NSFW fileshare. ro - ads
||fileshare.ro/banners/
||simpatie.ro^$third-party
fileshare.ro##[width="250"][valign="top"]
```

the last from the above is to address unhidden space after the blocking occured

edit: edited the second filter

another edit:

`http://www.girlshare.ro/3769879103.1`

```
||sexlab.ro^$domain=girlshare.ro
girlshare.ro#?#td > center:-abp-contains(Reclama)
```

instead of `girlshare.ro#?#td > center:-abp-contains(Reclama)`, it could be added to the cosmetic filter for [NSFW] `fileshare dot ro`

**Comment by playonevideo** [comment]
Ads at simpatie and sex pills on `https://fileshare.ro/e3172788300`
