### ISSUE TITLE
divahair.ro + qbebe.ro

### ISSUE THREAD

**Issue by BlocksAds** [tcptomato/ROad-Block#349]
I suppose a `redirect` filter could be added for `divahair.ro` `https://www.divahair.ro/jurnalul-divei/un-tanar-de-37-de-ani-i-a-returnat-geanta-cu-bani-unei-batrane-de-93-de-ani-si-au-devenit-cei-mai-buni-prieteni?utm_source=qbebe.ro&utm_medium=site&utm_campaign=from-qbebe` (around the middle of the page)

And the same for `qbebe.ro` `https://www.qbebe.ro/retete_culinare/2_-_4_ani/mancaruri-de-post-retete-care-vor-incanta-si-copiii` (scroll to where the where the video content should be)

**Comment by mapx-** [comment]
I don't understand which is the issue: breakage ? ads ?

**Comment by BlocksAds** [comment]
- `redirect` was not used in road-block lite for `divahair.ro`
- `https://www.qbebe.ro/retete_culinare/2_-_4_ani/mancaruri-de-post-retete-care-vor-incanta-si-copiii` -> anti-adb
