### ISSUE TITLE
please delete a line

### ISSUE THREAD

**Issue by moi1812** [tcptomato/ROad-Block#353]
Pagină URL (necesar) :  https://fr.sputniknews.africa/

there is an fucking idiot yesterday whos added the line "||sputniknews.*^$all" in the list.... what's about freedom press ?
![2](https://user-images.githubusercontent.com/128904673/227716692-ec4266b1-2efc-4ca1-bccc-8c8ee081df72.jpg)

**Comment by mapx-** [comment]
https://www.consilium.europa.eu/en/press/press-releases/2022/03/02/eu-imposes-sanctions-on-state-owned-outlets-rt-russia-today-and-sputnik-s-broadcasting-in-the-eu/

EU imposes sanctions on state-owned outlets RT/Russia Today and Sputnik's broadcasting in the EU
EU will urgently suspend the broadcasting activities of Sputnik’ and RT/Russia Today

https://rm.coe.int/note-rt-sputnik/1680a5dd5d

![image](https://user-images.githubusercontent.com/10303732/227718153-f46fb30d-430e-4188-a673-75ac861fb35a.png)
