### ISSUE TITLE
ardereaesteproblema.ro

### ISSUE THREAD

**Issue by pancakeexpert** [tcptomato/ROad-Block#355]
I never would've believed that tobacco companies could use resources like this in the European Union. I suspected something weird about this campaign.

`ziare.com` => 'arderea este problema' (equivalent in English: "the burning is the problem") ad => page with tobacco-related articles => `https://www.stiripesurse.ro/philip-morris-romania-a-fost-recunoscuta-drept-angajator-de-top-pentru-al-noualea-an-consecutiv_2756905.html` -- At the end of the article: 
![image](https://user-images.githubusercontent.com/130928216/232340359-99d14410-cf8a-44e6-aa40-dd0a27167827.png) (in english, that last phrase could be translated to "Article sustained by Philip Morris Romania".

Also, proof about `https://ardereaesteproblema.ro/`: `https://ardereaesteproblema.ro/docs/Termeni-de-utilizare-a-paginilor-de-socializare-corporative-si-confidentialitatea-datelor-Arderea-este-problema.pdf`: 
![image](https://user-images.githubusercontent.com/130928216/232340452-f8c110a0-cb36-47fb-abfc-ef43afcc5813.png)

```
stiripesurse.ro##div.article-category-container.md-one-half.ld-one-half.column:nth-of-type(3):has([href*="philip-morris-romania-a-fost-recunoscuta-drept-angajator-de-top-pentru-al-noualea-an-consecutiv_2756905.html"])
! for road-uBO
||ardereaesteproblema.ro^$doc
||stiripesurse.ro/ardereaesteproblema/$doc
! Allegedly sustained by Philip Morris Romania
||stiripesurse.ro/philip-morris-romania-a-fost-recunoscuta-drept-angajator-de-top-pentru-al-noualea-an-consecutiv_2756905.html$doc
```

And if this all sounds ridiculous, look into who owns and operates certain "alternative" tobacco products. (you know, the ones that "heat" it)
Edit: I am not talking exactly about vapes
https://en.wikipedia.org/wiki/Iqos

Also, similar situation in my opinion: https://github.com/tcptomato/ROad-Block/blob/caf6fb96ed12c3e1c778f9d643ecf102c11e7aba/road-block-filters-light.txt#L837

**Comment by mapx-** [comment]
maybe

```
stiripesurse.ro##.article-category:has-text(/Philip Morris|țigar/)
stiripesurse.ro##.article-category-featured:has-text(Philip Morris)
```

I get no "arderea" on `ziare.com`

**Comment by pancakeexpert** [comment]
> I get no "arderea" on `ziare.com`

maybe it was blocked/hidden by road-block lite
anyhow, I believe `arderea este problema` - `ardereaesteproblema.ro` is a campaign from Philip Morris Romania ... I saw advertising on YouTube as well

I believe users should recieve a better hint of a possible conflict of interests with `||ardereaesteproblema.ro^$doc`

**Comment by mapx-** [comment]
- well, it's a legitimate site, no malicious stuff
- if you tell me links toward that site which are on some romanian page I'd block it

**Comment by pancakeexpert** [comment]
@tcptomato

**Comment by pancakeexpert** [comment]
@gorhill Wouldn't you say that big tobacco propaganda, if this were to be such a thing, could be blocked by this list?

**Comment by advertblocking** [comment]
But could `||ardereaesteproblema.ro^$doc` be added for uBO and AdGuard users also?

**Comment by mapx-** [comment]
No.

**Comment by advertblocker** [comment]
https://github.com/tcptomato/ROad-Block/blob/d236b5f021bc2f027ae505d6d64315e0df95b7a7/road-block-filters-light.txt#L1599
https://github.com/tcptomato/ROad-Block/blob/d236b5f021bc2f027ae505d6d64315e0df95b7a7/road-block-filters-light.txt#L1604

uBO linter errors
