### ISSUE TITLE
Support for Moldovan websites?

### ISSUE THREAD

**Issue by DandelionSprout** [tcptomato/ROad-Block#38]
Greetings, Dandelion Sprout here, the maintainer of a Nordic adblock list and an adblocking enthusiast in general.

As a part of my personal ongoing campaign to improve and assist lists that are included in uBlock Origin (Especially the regional ones), I decided to map out which countries in Europe there were that weren't covered by any of uBO's regional lists, and saw that Moldova was one of the very few non-Balkan ones.

So since Wikipedia tells me that the Romanian and Moldovan languages are for most intents and purposes identical, I figured that your list could've been a good one to cover the country of Moldova with.

I've written some entries, but I was unsure how the category structure of the ROad-block text files worked like, so I'll let you guys decide how to do so and/or to test out the entries:

```
##.richmedia_fisc
agora.md##div.grey-section:-abp-contains(Advertorial)
curentul.md###banner1
curentul.md###banner5
curentul.md###banner6
curentul.md###hightopbanner
curentul.md###logorow > a[style="margin-left:30px"]
curentul.md###meteo
curentul.md##.floating
curentul.md##div#banner3:nth-of-type(6)
hotnews.md##.adv
istoria.md##div.d2011-block-lateral-middle:-abp-has(a[href*="voceabasarabiei.net"])
istoria.md##div:nth-of-type(3) > object > embed
poliexpert.md##.banner
protv.md###idvop_fbl
radiochisinau.md##.adds
shok.md##.right_side > div:nth-of-type(2)
stirinonstop.md###Wbanner300x250 > .maxima_zilei
stirinonstop.md##.numbers-promo-placeholder
timpul.md##.numbers-promo-placeholder
timpul.md##.widget_text
tribuna.md###hightopbanner
||curentul.md/wp-content/banners/
```

Does this sound like a good idea to you guys, or?

**Comment by tcptomato** [comment]
Thanks for the post. All add them when I get home.

**Comment by tcptomato** [comment]
Forgot to close it.
