### ISSUE TITLE
turdanews.net

### ISSUE THREAD

**Issue by advertblocker** [tcptomato/ROad-Block#383]
`https://turdanews.net/fotbal-liga-4-un-nou-scandal-in-jurul-ajf-cluj-ariesul-mihai-viteazu-ameninta-cu-retragerea-din-campionat/` => placeholders between top menu and article title
```
turdanews.net##.e-con
```

there's also an announcement, supposedly for hiring, `turdanews.net##.ai-track` tracks it and some other placeholders placed within the article

**Comment by AlmondPie** [comment]
`https://turdanews.net/`
- ad
- placeholders

```
turdanews.net##.ai-track
```
