### ISSUE TITLE
Luju.ro - Logo blocat

### ISSUE THREAD

**Issue by ArmynC** [tcptomato/ROad-Block#39]
Pagină URL (necesar) : luju.ro
Screenshot (optional)  : -

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.

Am observat ca s-a incercat blocarea reclamelor trecute sub forma de resurse-imagini (`/luju\.ro\/static\/images\/[a-zA-Z0-9=,.?&]+$/$image,domain=luju.ro`) insa printre ele exista si mai multe logo-uri si legaturi... Cateva exemple:

Legaturi (a nu se considera ca reclame):
https://www.luju.ro/static/images/1.jpg
https://www.luju.ro/static/images/unbr2.png
https://www.luju.ro/static/images/banias.jpg
https://www.luju.ro/static/images/ueb.jpg
https://www.luju.ro/static/images/jurindex.jpg

Structura site-ului
https://www.luju.ro/static/images/en.jpg
https://www.luju.ro/static/images/ladylft.jpg
https://www.luju.ro/static/images/ladyrht.jpg
https://www.luju.ro/static/images/home.jpg
https://www.luju.ro/static/images/logo.jpg
https://www.luju.ro/static/images/shadow.jpg

**Comment by tcptomato** [comment]
Am adaugat elementele din structura site-ului care au fost prinse de filtru. Cat despre legaturile care zici ca nu sunt reclama, let's agree to disagree.

**Comment by ArmynC** [comment]
Hmm.. cel putin la jurindex si unbr nu vad de ce ar fi reclame.

Exemplu: 

> Jurindex este un serviciu gratuit, care-şi propune să ofere accesul liber la hotărârile judecătoreşti pronunţate de instanţe. Jurindex se află sub egida Consiliului Superior al Magistraturii

**Comment by tcptomato** [comment]
Le-am pus in whitelist.
