### ISSUE TITLE
Reclame neblocate

### ISSUE THREAD

**Issue by lipici** [tcptomato/ROad-Block#40]
Pagină URL (necesar) :https://lp.maxbet.ro/50ron-gratis-joc/?btag=2191749-311fdlp52k2i4047&utm_source=adst&utm_campaign=171401

Screenshot (optional)  : https://i.imgur.com/mpleHFe.png

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.

Nu blocheaza toate reclamele cum este exemplul de mai sus si multe reclame se deschid in tab nou chiar dar nu le afiseaza , normal tab-ul ar trebui sa fie inchis /blocat  sa nu se ajunga la redirect

**Comment by tcptomato** [comment]
Sorry de raspunsul tarziu, dar mi-a mancar nervii site-ul acesta. Nu ma pot inregistra indiferent de browserul folosit, de ISP, de nimic. Am incercat din orase/tari diferite si nimic. Ai cumva posibilitatea sa gasesti tu scriptul care deschide reclamele in tab-uri noi?

**Comment by lipici** [comment]
salut, mersi de raspuns
este unul din astea :
https://vy4e3jw46l.com/sound?key=0f22c1fd609f13cb7947c8cabfe1a90d&psid=14892298https://lp.maxbet.ro/50ron-gratis-joc/?btag=2191749-85b3awf8wxrwjfb3&utm_source=adst&utm_campaign=171401https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=rhttps://vy4e3jw46l.com/https://vy4e3jw46l.com/sound?

https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=r








    On Wednesday, February 27, 2019, 3:45:00 PM GMT+2, Thomas Böhm <notifications@github.com> wrote:  
 
 
Sorry de raspunsul tarziu, dar mi-a mancar nervii site-ul acesta. Nu ma pot inregistra indiferent de browserul folosit, de ISP, de nimic. Am incercat din orase/tari diferite si nimic. Ai cumva posibilitatea sa gasesti tu scriptul care deschide reclamele in tab-uri noi?

**Comment by lipici** [comment]
salut, mersi de raspuns
este unul din astea :
https://vy4e3jw46l.com/sound?key=0f22c1fd609f13cb7947c8cabfe1a90d&psid=14892298https://lp.maxbet.ro/50ron-gratis-joc/?btag=2191749-85b3awf8wxrwjfb3&utm_source=adst&utm_campaign=171401https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=rhttps://vy4e3jw46l.com/https://vy4e3jw46l.com/sound?

https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=r
    On Thursday, February 28, 2019, 7:17:17 AM GMT+2, No No <campeones1923@yahoo.com> wrote:  
 
  salut, mersi de raspuns
este unul din astea :
https://vy4e3jw46l.com/sound?key=0f22c1fd609f13cb7947c8cabfe1a90d&psid=14892298https://lp.maxbet.ro/50ron-gratis-joc/?btag=2191749-85b3awf8wxrwjfb3&utm_source=adst&utm_campaign=171401https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=rhttps://vy4e3jw46l.com/https://vy4e3jw46l.com/sound?

https://vy4e3jw46l.com/soundcver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrents.php&kw=%5B%22rarbg%22%2C%22torrents%22%2C%22filmi%22%2C%22download%22%5D&key=9ef78edf998c4df1e1636c9a474d9f47&scrWidth=1920&scrHeight=1080&tz=2&ship=&pst=&res=4.31&dev=r








    On Wednesday, February 27, 2019, 3:45:00 PM GMT+2, Thomas Böhm <notifications@github.com> wrote:  
 
 
Sorry de raspunsul tarziu, dar mi-a mancar nervii site-ul acesta. Nu ma pot inregistra indiferent de browserul folosit, de ISP, de nimic. Am incercat din orase/tari diferite si nimic. Ai cumva posibilitatea sa gasesti tu scriptul care deschide reclamele in tab-uri noi?

**Comment by tcptomato** [comment]
Le-am adaugat, dar din pacate nu le pot testa pe site. Imi spui te rog daca functioneaza cum trebuie?

**Comment by lipici** [comment]
Salut, multumesc.
Confirm ca este ok, doar ca au adaugat altul  sau are un fel de back-up, pana acum nu a aparut niciodata xzipy.com :(Il poti adauga si pe acesta?
https://xzipy.com/sound?cver=1&refer=https%3A%2F%2Frarbgp2p.org%2Ftorrent%

    On Thursday, March 7, 2019, 1:23:46 PM GMT+2, Thomas Böhm <notifications@github.com> wrote:  
 
 
Le-am adaugat, dar din pacate nu le pot testa pe site. Imi spui te rog daca functioneaza cum trebuie?

**Comment by tcptomato** [comment]
L-am adaugat. Dureaza vreo 5 minute pana e sincronizata lista pe website, si atunci va trebui sa faci update manual in browser ( sau sa astepti 1 zi pana se actualizeaza).

**Comment by lipici** [comment]
Un mare multumesc. 
    On Thursday, March 7, 2019, 8:20:39 PM GMT+2, Thomas Böhm <notifications@github.com> wrote:  
 
 
L-am adaugat. Dureaza vreo 5 minute pana e sincronizata lista pe website, si atunci va trebui sa faci update manual in browser ( sau sa astepti 1 zi pana se actualizeaza).
