### ISSUE TITLE
$doc / window-close-if scriptlet for betting sites

### ISSUE THREAD

**Issue by advertblocker** [tcptomato/ROad-Block#401]
I've seen a pattern of betting sites / affiliate links appearing via popunders.

On the same grounds a scriptlet was added for `norton.com`, could some betting sites be addressed either here or in uAssets?

(with affiliate / advertising params)

**Comment by mapx-** [comment]
You have to provide steps/explanations to be able to reproduce such problems.
I'd say it's better open a discussion here:
https://github.com/uBlockOrigin/uAssets/discussions
