### ISSUE TITLE
infotv.ro

### ISSUE THREAD

**Issue by advertblocker** [tcptomato/ROad-Block#405]
`https://info1tv.ro/dan-air-devine-prima-companie-aeriana-de-linie-care-opereaza-zboruri-de-pe-aeroportul-international-brasov-ghimbav/` => ads above title + ad in right sidebar (the facebook page seems to be theirs or affiliated)

```
||info1tv.ro/*-pixel.gif$image
||info1tv.ro/*/2020/11/*.gif$image
info1tv.ro##[href="http://www.april91.ro/"]
info1tv.ro#?#[id^="custom_html"]:-abp-has([alt^="Agentie"])
```
the reason I used `id^` is because there were multiple ids being used anyway

I don't know about the "LIVE Studio TV" widget

**Comment by waterfluoridation** [comment]
@mapx- 
```
||info1tv.ro/*banner$image
```
![image](https://github.com/user-attachments/assets/0958df2b-2b78-4da8-a383-5eda49bbc239)
