### ISSUE TITLE
ph-online.ro ads

### ISSUE THREAD

**Issue by mapx-** [tcptomato/ROad-Block#41]
Pagină URL (necesar) :
(fake news) `http://ph-online.ro/politica/item/82153-presedintele-cedo-noi-am-cerut-gratierea-in-romania-practic-romanii-protesteaza-impotriva-ue-si-cedo-de-ce-nu-se-duc-la-strasbourg-la-bruxelles`

```
||ph-online.ro/*banner
ph-online.ro##.banneritem
||connect.facebook.net/ro_RO/all.js$script,domain=ph-online.ro
```

last one reason => any refresh of the page you'll get FB-like proposal, very annoying

**Comment by tcptomato** [comment]
Thanks, added.
