### ISSUE TITLE
referatele.com ads

### ISSUE THREAD

**Issue by mapx-** [tcptomato/ROad-Block#42]
Pagină URL (necesar) : `http://www.referatele.com/referate/noi/jurnalism/vizita-si-voiajul-de3101220523.php`

ads from m4clicks.com, ad.mox.tv (`Mediawayss AD TECH – Complex video and display monetization`)

```
||m4clicks.com^$third-party
||ad.mox.tv^
||ecoduri.com/imagini/ecoduri.gif$image
```

**Comment by tcptomato** [comment]
Thanks. added.
