### ISSUE TITLE
(NSFW) filme-porno. ro, eporno. ro

### ISSUE THREAD

**Issue by bookarticle** [tcptomato/ROad-Block#428]
- webcam-type ads
- ad around the lower-right corner of the screen
- pre-roll

```
||pornlash.com^
eporno.ro,filme-porno.ro##.cxADBlock
eporno.ro,filme-porno.ro##.videoPlayerAD
||femeisingure.net^$doc
||easyaff.net/?ref$doc
```

`easyaff.net` href from preroll

**Comment by pilis1** [comment]
`e-porno.ro` has ad leftovers

https://github.com/user-attachments/assets/247c61c1-4e9d-4a99-b60d-2ba5e2a10dd2

**Comment by ghost** [comment]
popups if you click any link on the page
<img width="944" height="622" alt="Image" src="https://github.com/user-attachments/assets/e96d8420-7f38-404e-8f4b-8dd6c4e311e2" />

**Comment by mapx-** [comment]
> click any link on the page

provide page link

**Comment by ghost** [comment]
e-porno.ro, go to the site and click any video on it

**Comment by playonevideo** [comment]
On `https://filmexxx.ro/blonda-ispititoare-ofera-muie-adanca` there are ads at AI chat before video starts.

**Comment by playonevideo** [comment]
Popups on `https://e-porno.ro/`
