### ISSUE TITLE
ququlioco.info

### ISSUE THREAD

**Issue by bookarticle** [tcptomato/ROad-Block#435]
`https://ququlioco.info/lp/ena/RO/8512434_Ostex_RO/?clickid=5fef5d030ac5170236ff676fae516dec-5962-0522&cpa=cpa,peerclick&adn_id=adn_id,17&bidid=bidid,SCB-283-ssp-5cb8aaba-bd5e-3e25-f621-f621-cdbd334fa5-lhz8o68m-1oqv&impid=impid,SCI-283-753707-lhz8o68m-vpb_0&creative_id=creative_id,157032&site_id=site_id,452415&geo=geo,ROU&creo_pair=creo_pair,0-%3E8605&c_type=c_type,DR&click_date=click_date%C2%B6ms=params,1684783626&req_date=YW5pbT0wJmFuaW1hdGlvbj0wLjAwMDAwMCZiaWRpZD1TQ0ItMjgzLXNzcC01Y2I4YWFiYS1iZDVlLTNlMjUtZjYyMS1mNjIxLWNkYmQzMzRmYTUtbGh6OG82OG0tMW9xdiZicnV0YWxfcmF0ZT0wJmNfdHlwZT1EUiZjYW1wX2lkPTAmY2xpY2tfZGF0ZT0xNjg0NzgzNjI2JmNwYT1wZWVyY2xpY2smY3Jlb19wYWlyPTAtJTNFODYwNSZkZXZpY2U9MiZkZXZpY2VfbGFuZz1lbiZlbmRwb2ludD1tYWluJmVzdWJfZm9yX3Nob3A9Jmdlbz1ST1UmaWFiPUlBQjctMTQtMS0yJmltcGlkPVNDSS0yODMtNzUzNzA3LWxoejhvNjhtLXZwYl8wJmltcGlwPTE0Ni43MC4xMjQuMTYzJnNleF9yYXRlPTAmc2hvd19icnV0YWxfcmF0ZT0yLjAwMDAwMCZzaG93X3NleF9yYXRlPTEuMDAwMDAwJnNpdGVfbGFuZz1ybyZzdWJjYW1wX2lkPTAmdGFnX2lkPTc1MzcwNyZ0eXBlX2FwcHJvdmU9MSZ1aWQ9MTk1MWI3OGUtMDM5Yi00ZWM3LWJmM2EtMDZlYTUxY2MyYjA3JnVzZXJfaWQ9MCZ1c2VyX3NhZmVfaWQ9&cid=uid,1951b78e-039b-4ec7-bf3a-06ea51cc2b07&endpoint=endpoint,main&rk_id=7571#`

romaniatv article (uBO disabled) => opened from an adnow ad

**Comment by bookarticle** [comment]
@Yuki2718 you're good at generic filters; any suggestions?

**Comment by mapx-** [comment]
Provide the steps to reproduce the ...issue ? 

uBO disabled ?

**Comment by bookarticle** [comment]
`https://www.romaniatv.net/surse-nicolae-ciuca-isi-depune-vineri-mandatul-de-premier_7487666.html` (uBO disabled) => scrolled down => accessed a link from an ad

<details> <summary> Screenshot </summary>

![image](https://github.com/tcptomato/ROad-Block/assets/134229975/2afda2af-e061-43bd-8e62-77a4e1e278f8)

</details>

I don't know if you visited the web page, but I am not a fun of such ads

**Comment by bookarticle** [comment]
Yep, the "ad" is lying
![image](https://github.com/tcptomato/ROad-Block/assets/134229975/1e5b782b-4423-4f72-8452-d49e74a60bac)

**Comment by mapx-** [comment]
Do not click all the ads in this world, just keep uBO enabled.

**Comment by bookarticle** [comment]
That's beyond the point; such websites could be added to sites like facebook (where, you know, uBO is fought)
