### ISSUE TITLE
https://www.europafm.ro/live    banner ads

### ISSUE THREAD

**Issue by seba2282** [tcptomato/ROad-Block#46]
Pagină URL (necesar) :  https://www.europafm.ro/live
Screenshot (optional)  : 
![Screenshot_2019-03-28-21-47-50](https://user-images.githubusercontent.com/16944478/55193138-702e1500-51a6-11e9-8cc9-0581f793a8d9.png)

Banner under player.

**Comment by tcptomato** [comment]
Done :) Mersi de report
