### ISSUE TITLE
national.ro ads

### ISSUE THREAD

**Issue by mapx-** [tcptomato/ROad-Block#47]
```
national.ro#?#.clear:-abp-has(a)
national.ro##.metasingle-jos
national.ro###ys-container
national.ro##.visible.ys-layer
```

- first one => ads on right side (only home page), uBo format `national.ro##.clear:has(a)`  but it's ok the ABP format too (uBo converts it, ABP converts ...nothing)
- second filter => horrible ads in the middle of the articles pages
- 3th, 4th => annoying overlay on clicking every new article

**Comment by tcptomato** [comment]
Thanks :)
