### ISSUE TITLE
uniondht.org

### ISSUE THREAD

**Issue by DogancanYr** [tcptomato/ROad-Block#511]
It doesn't do anything other than blocking the actual magnet button and the site youpic.su is down.

Delete : uniondht.org,youpic.su##a[href*="rutor."]

**Comment by mapx-** [comment]
You are talking about the russian list (not the romanian one)

@dimisa-RUAdList

magnet link hidden here for example:
https://uniondht.org/topic/1854396-klyatva-yemin.html

**Comment by DogancanYr** [comment]
I didn't pay attention to where I wrote. (I meant it hides the button.)

**Comment by mapx-** [comment]
I've notified the russian list maintainer

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/9169e3fa5122f6133cafbf6019e375c8f782adc3

**Comment by DogancanYr** [comment]
> Fix: [easylist/ruadlist@9169e3f](https://github.com/easylist/ruadlist/commit/9169e3fa5122f6133cafbf6019e375c8f782adc3)

With the new code, it was the same as before.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/eb528fd1bd6cc796c8120d9535fcc4519d71e151

**Comment by DogancanYr** [comment]
> [easylist/ruadlist@eb528fd](https://github.com/easylist/ruadlist/commit/eb528fd1bd6cc796c8120d9535fcc4519d71e151)

It's the same again, can't you just delete the code completely?

**Comment by dimisa-RUAdList** [comment]
I don't see any problems. Make sure you are using the actual version of RU AdList. 

For further discussion please use: https://github.com/easylist/ruadlist/issues
