### ISSUE TITLE
stiripesurse.ro ads

### ISSUE THREAD

**Issue by mapx-** [tcptomato/ROad-Block#52]
example page:
`https://www.stiripesurse.ro/liviu-dragnea-confruntare-cu-malin-bot-in-sala-de-judecata-replica-nervoasa-a-liderului-psd_1342107.html`

```
stiripesurse.ro##.banner
||media.stiripesurse.ro/assets/img/ads_img/$image
```

**Comment by tcptomato** [comment]
Thanks :)
