### ISSUE TITLE
prosport.ro broken

### ISSUE THREAD

**Issue by mapx-** [tcptomato/ROad-Block#56]
Pagină URL (necesar) : 
`https://tacataca.prosport.ro/poze/oana-roman-din-ce-in-ce-mai-sexy-de-cand-a-slabit-vedeta-a-trecut-la-fuste-scurte-si-mulate-27315`

The slide show is broken due to this filter:
`||prosport.ro^$inline-script`

disabling in uBo the filter
`||prosport.ro^$inline-script,badfilter`
I get back the correct functionality of the page

Which was the original issue ?

**Comment by tcptomato** [comment]
Thanks for the report.

I tried your link, and for me the slideshow works. Only one picture isn't displayed, the third, and it looks like it's an ad ( the URL ends in ?pic=ad-27319). Is this the issue you also experience?

The issue was probably an anti-adblock script inlined in the main page.

**Comment by mapx-** [comment]
Tested again in chrome / brave => same issue: I can see only 1 photo then all is blocked.
Disabling that filter it's the fix for me.

**Comment by tcptomato** [comment]
I commented the rule out and will keep an eye on the website.

**Comment by MicrowaveSnacks** [comment]
https://github.com/tcptomato/ROad-Block/assets/134642685/10c9854b-3182-4863-81e8-418ccf785778
```
||prosport.ro/w*betano-$image
``
