### ISSUE TITLE
ads on some romanian websites

### ISSUE THREAD

**Issue by ghost** [tcptomato/ROad-Block#74]
#62 follow up
`||www.sfatulmedicului.ro/external/img/adds*` seems to fix the issue with the ads on sfatulmedicului.ro
`opiniatimisoarei.ro##[href="https://www.rapidauto.ro/ro/content/showroom-timisoara.html"]` seems to fix the issue on opiniatimisoarei.ro;I'm not sure if it's the best way to do so
ziarulconstanta.ro has some spaces

**Comment by tcptomato** [comment]
Done. Sorry de delay.

**Comment by seedoils** [comment]
`https://www.sfatulmedicului.ro/Diverse/patologia-chirurgicala-a-tiroidei_17348` => advertising in right sidebar

```
||sfatulmedicului.ro/*/images/banner
sfatulmedicului.ro###promoClk
```
