### ISSUE TITLE
Images appear on clubopel.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#76]
Pagină URL (necesar) : www.clubopel.ro

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde filtrul nu funcționează.
I see some images between posts and I want to remove them. Here is the filter which worked for me: *.gif$domain=clubopel.com,image

**Comment by tcptomato** [comment]
Thanks. I added your rule to the script. I tried some less blunt rules, but the adds are loaded again by some anti ad block functionality.
