### ISSUE TITLE
Some filters that maybe should be added

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#82]
Here is the link: https://www.officeshoes.ro/
And this is the filter: ||cdn.scarabessearch.com^

And other link: https://www.olx.ro/
And those filters: ||static.hotjar.com^
||creativecdn.com^

I found these filters on some non-maintained anymore lists and maybe are worth adding.

**Comment by IThinkIAmCool** [comment]
Why exactly should they be added?

**Comment by mapx-** [comment]
all those filters are already included in EP / EL:

```
https://www.olx.ro/ => EasyPrivacy => ||scarabresearch.com^$3p
https://www.olx.ro/ => EasyPrivacy => ||hotjar.com^$third-party
					   EasyList => ||creativecdn.com^

```
