### ISSUE TITLE
mediafax.ro

### ISSUE THREAD

**Issue by IThinkIAmCool** [tcptomato/ROad-Block#83]
Pagină URL (necesar) : https://www.mediafax.ro/

There is a livestream that is automically played, I'm not sure if it could be addressed in this repository.

encountered while using uBlock Origin(default filter lists + ROU: Romanian Ad (ROad) Block List Light)

**Comment by tcptomato** [comment]
I filtered the second video which looked like an ad. The first one looks like its their "breaking news" story.
