### ISSUE TITLE
Ads on roumanian websites

### ISSUE THREAD

**Issue by gemoshi07** [tcptomato/ROad-Block#87]
https://www.reddit.com/r/uBlockOrigin/comments/o6bqy4/websites_with_place_holders/

**Comment by tcptomato** [comment]
Not sure what the ads are here. Could you please post here the links to the pages where you have the issues.

**Comment by gemoshi07** [comment]
@tcptomato Yes, here they are:
https://www.escortebucuresti.com/ with https://imgur.com/a/RVL8EG8
https://nimfomane.com/ with https://imgur.com/a/5FhDdec
https://nimfomane.com/forum/forum/49-escorte-testate-bucuresti/ with https://imgur.com/a/UCulmcG
https://nimfomane.com/forum/topic/180564-lia-❤️❤️❤️-in-vizita-🤗❤️-0790475094/ with https://imgur.com/a/zw5Oymr

**Comment by tcptomato** [comment]
Done
