### ISSUE TITLE
4tuning.ro - placeholders

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#93]
Pagină URL (necesar) :
`https://www.4tuning.ro/` 
`https://www.4tuning.ro/alte-stiri-auto/ar-putea-fi-inceputul-unei-noi-ere-comisia-europeana-propune-oficial-interzicerea-vanzarilor-de-masini-pe-benzina-si-motorina-47023.html`
`https://anunturi-auto.4tuning.ro/`
`https://anunturi-auto.4tuning.ro/fata-completa/vw/golf-5/fata-completa-vw-golf-5-plus-2005-2008-1344020.html`

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
I see some placeholders on this website and I hope they can be removed. 
For first link:
![screen-1](https://user-images.githubusercontent.com/79897301/129094746-c5fc0857-55e5-4917-9213-d21c05771fe8.jpg)
For 2nd link:
![screen02](https://user-images.githubusercontent.com/79897301/129094774-f559513b-df6e-48ab-8024-b076948d73df.jpg)
For 3rd link:
![screen03](https://user-images.githubusercontent.com/79897301/129094788-e0a98f00-5026-41f0-8937-458389883a88.jpg)
For 4th link:
![screen04](https://user-images.githubusercontent.com/79897301/129094809-ba1822a2-55b7-4277-8f2c-3ae5c66fd421.jpg)

**Comment by andreewmat** [comment]
Also, on https://www.olx.ro/ I can't access categories like "Autoturisme" from "Auto, Moto si Ambarcatiuni" category.

**Comment by tcptomato** [comment]
Done
