### ISSUE TITLE
oradesibiu.ro ads and placeholders

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#95]
Pagină URL (necesar) : 
`https://www.oradesibiu.ro/`
`https://www.oradesibiu.ro/2021/07/29/comandamentul-nato-de-la-sibiu-va-fi-complet-operational-din-2024/`(here is the last screenshot)

Screenshot (optional)  :
![imageedit_1_3068255611](https://user-images.githubusercontent.com/79897301/127696093-38e0d2aa-5e26-4892-90d3-4c175c5076d7.gif)
![imageedit_1_2628033249](https://user-images.githubusercontent.com/79897301/127696107-667149e9-41c7-4ec2-b1e6-c10c36e6d2a2.gif)
![imageedit_1_2443423613](https://user-images.githubusercontent.com/79897301/127696121-447de6e1-1de8-4ec7-be0e-f8fccf7a9880.gif)
![imageedit_1_2554359425](https://user-images.githubusercontent.com/79897301/127696133-20717730-376d-4f33-8f8b-46a025d071b2.gif)

**Comment by tcptomato** [comment]
Done
