### ISSUE TITLE
cancan.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#96]
Pagină URL (necesar) : `https://www.cancan.ro/cati-lei-a-dat-un-turist-pe-4-nopti-de-cazare-intr-un-hotel-din-mamaia-suma-e-exorbitanta-20464672`

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
White banner
![screen04](https://user-images.githubusercontent.com/79897301/127783003-2814c72e-a62d-4dc8-897a-9f313e964c32.jpg)

**Comment by tcptomato** [comment]
Done
