### ISSUE TITLE
impact.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#97]
Pagină URL (necesar) : `https://www.impact.ro/anuntul-de-ultima-ora-facut-de-lidl-romania-alimentul-care-a-fost-retras-de-la-vanzare-210240.html`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
I see some placeholders here and there, maybe can be added to filter list.
![screen](https://user-images.githubusercontent.com/79897301/128210036-49c0b567-0d94-4741-83b5-cd7486748199.jpg)
![screen03](https://user-images.githubusercontent.com/79897301/128210374-b16d1452-715f-4fdd-ba79-32bf50779568.jpg)
![screen04](https://user-images.githubusercontent.com/79897301/128210543-0bf9ce10-197a-4fd1-8f52-daaeb0c1ccd7.jpg)
![screen01](https://user-images.githubusercontent.com/79897301/128210048-3e63c56b-a032-4b2c-bfa9-0692e4988eb9.jpg)
![screen02](https://user-images.githubusercontent.com/79897301/128210051-70c1f0d3-0c4b-41e6-b704-672c91cc4779.jpg)

**Comment by tcptomato** [comment]
Done
