### ISSUE TITLE
filmecrestineonline.ro

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#98]
Pagină URL (necesar) : `http://filmecrestineonline.ro/`
`https://filmecrestineonline.ro/the-family-that-preys-familia-care-se-roaga-2008/`
Screenshot (optional)  : https://imgur.com/a/9QIJpnv

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
I see some ads on the marked places on screenshots. And on a movie page, there is a "close" pop-up.

**Comment by tcptomato** [comment]
Done
