### ISSUE TITLE
pieseauto.ro cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [tcptomato/ROad-Block#99]
Pagină URL (necesar) `:https://www.pieseauto.ro/cablu-deschidere-usa/toyota/avensis/avensis-t25-break-combi-sw-facelift-2006-2007-1644196366.html`
Screenshot (optional)  :

[ro]Te rugăm să descrii ceea ce dorești să blochezi sau pagina unde lista de filtre nu funcționează corespunzător.
![imageedit_2_2588037874](https://user-images.githubusercontent.com/79897301/129094395-100c5906-9716-44b5-87e5-0dc6cf4c45ea.gif)

**Comment by tcptomato** [comment]
Done
